default_chain: stride-testnet
chains:
  stride-testnet:
    key: peyruz
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://0.0.0.0:26657
    grpc-addr: http://0.0.0.0:9090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  gaia-testnet:
    key: peyruz
    chain-id: GAIA
    rpc-addr: http://165.227.35.86:10657
    grpc-addr: http://165.227.35.86:10090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
